import '@/styles/globals.css';
import { type Metadata } from 'next';
import { auth } from '../server/auth';

import { TRPCReactProvider } from '@/trpc/react';
import StyledComponentsRegistry from '@/app/lib/registry';

import { LayoutClient } from '@/app/layoutClient';
import type { ISession } from '@/interfaces/interfaces';
import { Source_Code_Pro } from 'next/font/google';

const geist = Source_Code_Pro({
	subsets: ['latin'],
});

export const metadata: Metadata = {
	title: 'Create T3 App',
	description: 'Generated by create-t3-app',
	icons: [{ rel: 'icon', url: '/favicon.ico' }],
};

export default async function RootLayout({
	children,
}: Readonly<{ children: React.ReactNode }>) {
	const session = await auth();

	return (
		<html
			lang='en'
			data-theme='dark'
			style={{ colorScheme: 'dark' }}
			className={geist.className}
		>
			<body>
				<TRPCReactProvider>
					<StyledComponentsRegistry>
						<LayoutClient session={session as ISession | null}>
							{children}
						</LayoutClient>
					</StyledComponentsRegistry>
				</TRPCReactProvider>
			</body>
		</html>
	);
}
